### ISSUE TITLE
Other client implementations

### ISSUE THREAD

**Issue by aL3891** [Microsoft/service-fabric-client-dotnet#15]
Currently the client library is partially set up such that a non http version of the client could be implemented. For example there is a factory method that is not specific to http.
However that factory method is currently hard coded to use the http specific implementation. 

Are there other implementations planned for the foreseeable future? If not this abstraction layer seem to only add complexity and not offer much in return

**Comment by aL3891** [comment]
Allright, i'm no opposed to using interfaces at all, mainly I think the factory in common is a bit unnecessary, it doesn't add anything and has to use a bunch of reflection that is error prone. it seems better to just use each client directly.

Also, if other clients exist, why are they not in this repo?

**Comment by amanbha** [comment]
There could some scenarios in which user doesn't need to know what client is being used, he writes one piece of code and it works depending on cluster endpoint specified, if it's http, http client is used, if it's tcp, tcp client is used. We are not there yet, that's why this layer looks extra, but it keeps it open for future.

The tcp client is part of Service fabric runtime and c# managed code for it is not open sourced yet, it will be in it's separate repo at https://github.com/Microsoft/service-fabric
